version: '3.1'
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
        - PUID=1000
        - PGID=1000
    ports:
        - 27017:27017
    restart: unless-stopped
    
  cassandra:
    image: cassandra:3.11
    container_name: cadence-cassandra
    ports:
      - "9042:9042"
 
  cadence:
    image: ubercadence/server:master-auto-setup
    container_name: cadence-server
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cassandra
 
  cadence-web:
    image: ubercadence/web:latest
    container_name: cadence-web
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence