apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment
  labels:
    app: e-commerce-api

spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: e-commerce-api
    spec:
      containers:
      - name: e-commerce-api
        image: 774429751797.dkr.ecr.us-west-2.amazonaws.com/e-commerce-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
